### ISSUE TITLE
Support overwrite default commands

### ISSUE THREAD

**Issue by ZhiruiLi** [arjunmahishi/run-code.nvim#10]
If we run python code when we only installed python3, the result will be:

```log
zsh:1: command not found: python
```

It can be helpful if we can set default commands in setup function, something like:

```lua
require('run-code').setup {
  cmd = {
    python = "python3 <<-EOF\n%s\nEOF",
  }
}
```

**Comment by arjunmahishi** [comment]
Yep. Have been thinking about this for a while. But didn't know if there was a need. 
Will implement this now :) 

Thanks

**Comment by arjunmahishi** [comment]
@ZhiruiLi This is supported now. Check out the [example here](https://github.com/arjunmahishi/run-code.nvim#configuration) and let me know if it works :)
